### ISSUE TITLE
Not able to find the pretrained file

### ISSUE THREAD

**Issue by shashankMadan-designEsthetics** [NielsRogge/tapas_utils#2]
tapas-base-finetuned-sqa doesnt exists in hugging face neighter does [dropdox](https://www.dropbox.com/s/0ltfto59yvk9rua/tapas_base_finetuned_wtq_with_reset_and_intermediate_pretraining-20201017T093459Z-001.zip?dl=1) link exists...

Is it moved anywhere else?

**Comment by NielsRogge** [comment]
Hey,

yes that's because I've updated the model checkpoints. If you want to use tapas-base fine-tuned on SQA, I've got this notebook: https://colab.research.google.com/drive/1CDPUr7c8uCNnCtAmmFfj91j-sIzdcqym

Note that in the future, all checkpoints of the original repository](https://github.com/google-research/tapas) will be uploaded to the model hub of Hugging Face 😄

**Comment by shashankMadan-designEsthetics** [comment]
Wow, excited to hear that! (and hope it happens soon)

Thanks for the update.
